image: 
- macOS
- Ubuntu2204
- Visual Studio 2022

environment:
  major: 5
  minor: 8
  release: 0
  app_version: "$(major).$(minor).$(release).$(APPVEYOR_BUILD_NUMBER)"

version: "$(major).$(minor).$(release).{build}"

build_script:
  - cmd: build_Windows.bat
  - sh: chmod ugo+x buildNix.sh
  - sh: ./buildNix.sh


after_build:
  - cmd: createNugetPackage_Windows.bat %app_version%
  - sh: chmod ugo+x createNugetPackage_Nix.sh
  - sh: ./createNugetPackage_Nix.sh $app_version
  - ps: Get-ChildItem .\CVODES*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

skip_tags: true

skip_commits:
  files:
    - "*.md"

pull_requests:
  do_not_increment_build_number: true

nuget:
  disable_publish_on_pr: true
