name: Build PR for all supported platforms

on:
  pull_request:
    branches:
    - main

permissions:
  packages: read
  contents: read

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    with:
      app_version: 5.8.0.${{ github.run_number }}
      publish: false
    secrets: inherit
